-- 0002_riuka_web_tables.sql — tables the web dashboard needs that the base
-- schema has no equivalent for. Riuka-specific; no ponyo counterpart.
--
--   personal_notes   : notebook + real Postgres full-text search (generated
--                     tsvector column + GIN index, 'websearch' config).
--   chat_conversations / chat_messages : web AI-chat history (titles list +
                     messages per conversation).

create table if not exists public.personal_notes (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  notebook text not null default 'General',
  content text not null,
  content_tsv tsvector generated always as (to_tsvector('english', coalesce(content, ''))) stored,
  created_at timestamptz not null default now()
);
create index if not exists personal_notes_clan_time_idx on public.personal_notes (clan_tag, created_at desc);
create index if not exists personal_notes_notebook_idx on public.personal_notes (clan_tag, notebook);
create index if not exists personal_notes_content_tsv_idx on public.personal_notes using gin (content_tsv);

create table if not exists public.chat_conversations (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  title text not null default 'New chat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists chat_conversations_clan_recent_idx on public.chat_conversations (clan_tag, updated_at desc);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.chat_conversations (id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);
create index if not exists chat_messages_conversation_time_idx on public.chat_messages (conversation_id, created_at);

-- RLS: private per-clan data — no anon policies; server-side service-role only.
alter table public.personal_notes enable row level security;
alter table public.chat_conversations enable row level security;
alter table public.chat_messages enable row level security;
