-- 0001_init_schema.sql — Riuka base schema (captures the schema already applied
-- to the live Supabase project on 2026-09-19, written out idempotently so it
-- can be re-run on a fresh database without erroring).
--
-- Design rules baked into this schema:
--   * Event identity is instant-based. wars.war_key / capital_raids.season_key
--     are derived from CoC timestamps normalized to canonical UTC ISO instants
--     (see lib/transform.js cocStamp) — never from the raw API string, which
--     can shift by a second between polls or arrive in a different format.
--   * Every attack/member table has a natural-key unique constraint so the
--     poller can upsert safely and re-imports are idempotent.
--   * Participants are recorded even when they never attack (war_members /
--     capital raid absentees in capital_raids.data), because the CoC API only
--     lists members who already acted.
--   * RLS is enabled everywhere; data tables have read-only anon policies.
--     All writes happen server-side with the service-role key.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Clan + players
-- ---------------------------------------------------------------------------

create table if not exists public.clans (
  tag text primary key,
  data jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists public.players (
  tag text primary key,
  clan_tag text not null,
  name text not null,
  role text,
  town_hall_level integer,
  trophies integer,
  donations integer,
  donations_received integer,
  attack_wins integer,
  defense_wins integer,
  data jsonb not null,
  updated_at timestamptz not null default now()
);
create index if not exists players_clan_name_idx on public.players (clan_tag, name);

-- Rolling roster history: one row per player per snapshot batch; the sync
-- prunes to the SNAPSHOT_KEEP_BATCHES (default 12) most recent batches.
create table if not exists public.player_snapshots (
  id bigint generated by default as identity primary key,
  player_tag text not null,
  clan_tag text not null,
  captured_at timestamptz not null default now(),
  data jsonb not null
);
create index if not exists player_snapshots_player_time_idx on public.player_snapshots (player_tag, captured_at desc);

-- ---------------------------------------------------------------------------
-- Regular clan wars
-- ---------------------------------------------------------------------------

create table if not exists public.wars (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  war_key text not null unique,          -- instant-derived, see lib/transform.js
  state text,
  start_time timestamptz,
  end_time timestamptz,
  data jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists wars_clan_time_idx on public.wars (clan_tag, end_time desc);

create table if not exists public.war_members (
  id bigint generated by default as identity primary key,
  war_key text not null,
  clan_tag text not null,
  player_tag text not null,
  player_name text,
  map_position integer,
  attacks_available integer not null default 0,
  attacks_used integer not null default 0,
  stars_earned integer not null default 0,
  destruction_percentage double precision not null default 0,
  data jsonb not null,
  unique (war_key, clan_tag, player_tag)
);
create index if not exists war_members_war_idx on public.war_members (war_key);
create index if not exists war_members_player_idx on public.war_members (player_tag);

create table if not exists public.war_attacks (
  id bigint generated by default as identity primary key,
  war_key text not null,
  clan_tag text not null,
  attacker_tag text not null,
  attacker_name text,
  defender_tag text,
  defender_name text,
  stars integer,
  destruction_percentage double precision,
  order_no integer,
  attack_time timestamptz,
  duration_seconds integer,
  observed_at timestamptz default now(),
  data jsonb not null,
  unique (war_key, clan_tag, attacker_tag, order_no)
);
create index if not exists war_attacks_war_idx on public.war_attacks (war_key, order_no);
create index if not exists war_attacks_attacker_idx on public.war_attacks (attacker_tag);

-- ---------------------------------------------------------------------------
-- Clan War League (CWL)
-- ---------------------------------------------------------------------------

create table if not exists public.cwl_seasons (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  season_key text not null unique,       -- 'CWL:<season>', instant-derived
  data jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists public.cwl_rounds (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  season_key text not null,
  round_no integer not null,
  opponent_tag text,
  opponent_name text,
  state text,
  data jsonb not null,
  unique (season_key, round_no)
);

create table if not exists public.cwl_wars (
  id bigint generated by default as identity primary key,
  season_key text not null,
  war_tag text not null unique,          -- real CoC CWL war tag
  clan_tag text not null,
  opponent_clan_tag text,
  opponent_name text,
  state text,
  data jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists cwl_wars_season_idx on public.cwl_wars (season_key);

create table if not exists public.cwl_attacks (
  id bigint generated by default as identity primary key,
  season_key text not null,
  war_tag text not null,
  round_no integer not null default 0,
  clan_tag text not null,
  attacker_tag text not null,
  attacker_name text,
  defender_tag text,
  defender_name text,
  stars integer,
  destruction_percentage double precision,
  order_no integer,
  duration_seconds integer,
  attack_time timestamptz,
  observed_at timestamptz not null default now(),
  data jsonb not null,
  unique (war_tag, clan_tag, attacker_tag, order_no)
);
create index if not exists cwl_attacks_season_idx on public.cwl_attacks (season_key, round_no);
create index if not exists cwl_attacks_attacker_idx on public.cwl_attacks (attacker_tag, observed_at desc);
create index if not exists cwl_attacks_opponent_idx on public.cwl_attacks (defender_tag, observed_at desc);

-- ---------------------------------------------------------------------------
-- Clan Capital raids
-- ---------------------------------------------------------------------------

create table if not exists public.capital_raids (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  season_key text not null unique,       -- 'CR:<startTime instant>'
  data jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists public.capital_attacks (
  id bigint generated by default as identity primary key,
  season_key text not null,
  clan_tag text not null,
  opponent_clan_tag text,
  opponent_clan_name text,
  attacker_tag text not null,
  attacker_name text,
  district_id integer,
  district_name text,
  attack_number integer not null,
  stars integer,
  destruction_percentage double precision,
  duration_seconds integer,
  attack_time timestamptz,
  observed_at timestamptz not null default now(),
  data jsonb not null,
  unique (season_key, attacker_tag, district_id, attack_number, opponent_clan_tag)
);
create index if not exists capital_attacks_season_idx on public.capital_attacks (season_key, observed_at desc);
create index if not exists capital_attacks_attacker_idx on public.capital_attacks (attacker_tag, observed_at desc);
create index if not exists capital_attacks_opponent_idx on public.capital_attacks (opponent_clan_tag, observed_at desc);

-- ---------------------------------------------------------------------------
-- Observability + AI
-- ---------------------------------------------------------------------------

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  job text not null,
  status text not null,                 -- 'ok' | 'error'
  details jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.ai_answers (
  id uuid primary key default gen_random_uuid(),
  guild_id text,
  channel_id text,                      -- web usage: the chat conversation id
  user_id text not null,                -- web usage: 'web'
  message_id text,
  provider text not null,
  question text not null,
  full_answer text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null      -- 30-day retention; powers "See more"
);
create index if not exists ai_answers_expiry_idx on public.ai_answers (expires_at);
create index if not exists ai_answers_user_time_idx on public.ai_answers (user_id, created_at desc);

create table if not exists public.ai_conversations (
  id bigint generated by default as identity primary key,
  guild_id text,
  channel_id text,
  user_id text not null,
  provider text not null,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists ai_conversations_expiry_idx on public.ai_conversations (expires_at);
create index if not exists ai_conversations_scope_time_idx on public.ai_conversations (guild_id, channel_id, user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- RLS: enabled everywhere; anon gets read-only access to the data tables
-- (same policy shape the live database already uses). All writes go through
-- the server's service-role client, which bypasses RLS.
-- ---------------------------------------------------------------------------

alter table public.clans enable row level security;
alter table public.players enable row level security;
alter table public.player_snapshots enable row level security;
alter table public.wars enable row level security;
alter table public.war_members enable row level security;
alter table public.war_attacks enable row level security;
alter table public.cwl_seasons enable row level security;
alter table public.cwl_rounds enable row level security;
alter table public.cwl_wars enable row level security;
alter table public.cwl_attacks enable row level security;
alter table public.capital_raids enable row level security;
alter table public.capital_attacks enable row level security;
alter table public.sync_runs enable row level security;
alter table public.ai_answers enable row level security;
alter table public.ai_conversations enable row level security;

do $$
begin
  execute 'drop policy if exists "ai read clans" on public.clans';
  execute 'drop policy if exists "ai read players" on public.players';
  execute 'drop policy if exists "ai read snapshots" on public.player_snapshots';
  execute 'drop policy if exists "ai read wars" on public.wars';
  execute 'drop policy if exists "ai read war members" on public.war_members';
  execute 'drop policy if exists "ai read war attacks" on public.war_attacks';
  execute 'drop policy if exists "ai read cwl seasons" on public.cwl_seasons';
  execute 'drop policy if exists "ai read cwl rounds" on public.cwl_rounds';
  execute 'drop policy if exists "ai read cwl wars" on public.cwl_wars';
  execute 'drop policy if exists "ai read cwl attacks" on public.cwl_attacks';
  execute 'drop policy if exists "ai read capital raids" on public.capital_raids';
  execute 'drop policy if exists "ai read capital attacks" on public.capital_attacks';
end $$;

create policy "ai read clans" on public.clans for select to anon using (true);
create policy "ai read players" on public.players for select to anon using (true);
create policy "ai read snapshots" on public.player_snapshots for select to anon using (true);
create policy "ai read wars" on public.wars for select to anon using (true);
create policy "ai read war members" on public.war_members for select to anon using (true);
create policy "ai read war attacks" on public.war_attacks for select to anon using (true);
create policy "ai read cwl seasons" on public.cwl_seasons for select to anon using (true);
create policy "ai read cwl rounds" on public.cwl_rounds for select to anon using (true);
create policy "ai read cwl wars" on public.cwl_wars for select to anon using (true);
create policy "ai read cwl attacks" on public.cwl_attacks for select to anon using (true);
create policy "ai read capital raids" on public.capital_raids for select to anon using (true);
create policy "ai read capital attacks" on public.capital_attacks for select to anon using (true);

-- sync_runs / ai_answers / ai_conversations keep RLS with NO anon policies:
-- server-side only.
